version: '3'

services:
  hardhat:
    image: github.com/haapsee/nft-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hardhat
    ports:
      - "8545:8545"
    volumes:
      - .:/app
    working_dir: /app
    healthcheck:
      test: curl --fail http://localhost:8545/ || exit 1
      interval: 2s
    command: ["npx", "hardhat", "node"]
  app:
    image: github.com/haapsee/nft-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    volumes:
      - .:/app
    depends_on:
      hardhat:
        condition: service_healthy